### ISSUE TITLE
[Kotlindoc] Missing "dokkaRuntime" configuration

### ISSUE THREAD

**Issue by tlinkowski** [kordamp/kordamp-gradle-plugins#139]
When I apply the `kotlindoc` plugin, I get the following error: https://travis-ci.com/tlinkowski/tlinkowski-superpom/builds/117405671

Apparently, [simply creating an empty `dokkaRuntime` configuration](https://github.com/tlinkowski/tlinkowski-superpom/blob/15efa738308652dae93b74095fd3cc13bb34a1d1/build.gradle.kts#L184-L188) solves the problem: https://travis-ci.com/tlinkowski/tlinkowski-superpom/builds/117406767

**Comment by aalmiray** [comment]
Could you re-run with `-s` to get a full stacktrace? I'm not sure the problem is on the Kordamp plugin side as there are no explicit mentions of `dokkaRuntime` in its codebase. It might be related to the version of Kotlin/Dokka.

**Comment by tlinkowski** [comment]
There you go:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kotlindocHtml'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
	[... => more Gradle stuff]
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'dokkaRuntime' not found.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:150)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:323)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:140)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:58)
	at org.jetbrains.dokka.gradle.DokkaTask.generate(main.kt:301)
	[... => Java reflection stuff]
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
	[... => more Gradle stuff]
```

Let me know in case you needed me to debug the build to provide you with more details.

**Comment by aalmiray** [comment]
There's no mention of `org.kordamp` on that stacktrace, is it? Have you tried using a different version of Dokka?

**Comment by tlinkowski** [comment]
> There's no mention of `org.kordamp` on that stacktrace, is it?

No, there isn't.

> Have you tried using a different version of Dokka?

I haven't. But I don't even have an explicit dependency on Dokka. I just relied on your Kotlindoc plugin, and its documentation says:
> This plugin relies on the `org.jetbrains.dokka` plugin but does not apply it.

If it's easy to switch the version of Dokka and you'd like me to investigate this, please give me a hint on how I do it (I already found a workaround so I wouldn't like to spend too much time digging into it).

**Comment by aalmiray** [comment]
The `kotlindoc` plugins does not apply the `dokka` plugin as the latter may add configuration that's not suitable for a project.

You can update the dokka version by adding another classpath entry in the `buldscript` block.
