### ISSUE TITLE
Spotless plugin produces jgit incompatibility with kordamp buildinfo

### ISSUE THREAD

**Issue by wsargent** [kordamp/kordamp-gradle-plugins#173]
If you add the (spotless plugin](
https://github.com/diffplug/spotless/tree/master/plugin-gradle):

```
plugins {
    id 'org.kordamp.gradle.project' version '0.26.0'
    id 'org.kordamp.gradle.bintray' version '0.26.0'
    id 'com.gradle.build-scan'      version '2.2.1'
    id 'java'
    id "com.diffplug.gradle.spotless" version "3.24.2"
}
```

then you get

```
Caused by: groovy.lang.MissingMethodException: No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (String) values: [HEAD]
Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()
        at org.ajoberstar.grgit.service.BranchService.getCurrent(BranchService.groovy:61)
        at net.nemerosa.versioning.git.GitInfoService.getInfo(GitInfoService.groovy:49)
        at net.nemerosa.versioning.SCMInfoService$getInfo.call(Unknown Source)
        at net.nemerosa.versioning.VersioningExtension.computeInfo(VersioningExtension.groovy:195)
        at net.nemerosa.versioning.VersioningExtension.getInfo(VersioningExtension.groovy:182)
        at net.nemerosa.versioning.VersioningExtension_Decorated.getInfo(Unknown Source)
        at org.kordamp.gradle.plugin.buildinfo.BuildInfoPlugin.configureBuildProperties(BuildInfoPlugin.groovy:110)
        at org.kordamp.gradle.plugin.buildinfo.BuildInfoPlugin.access$0(BuildInfoPlugin.groovy)
        at org.kordamp.gradle.plugin.buildinfo.BuildInfoPlugin$_configureProject_closure1.doCall(Bu
```

**Comment by aalmiray** [comment]
This appears to be a classpath pollution problem due to conflicting versions for grgit. Will investigate.

**Comment by aalmiray** [comment]
I can't reproduce this problem. Even upgraded `spotless` to `3.24.3` and `build-scan` to `2.4.1` and no error.

**Comment by musketyr** [comment]
applying the following dependency to the project also breaks the build with the latest version:

```
classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.8.1'
```
