### ISSUE TITLE
Deactivate external package lists for dokka

### ISSUE THREAD

**Issue by leonard84** [kordamp/kordamp-gradle-plugins#364]
Is there a way to disable external package lookup in for `kotlindocHtml`?

```
Execution failed for task ':kotlindocHtml'.
> Guice provision errors:
  
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://docs.oracle.com/javase/6/docs/api/, packageListUrl=https://docs.oracle.com/javase/6/docs/api/package-list)
    at org.jetbrains.dokka.PackageListProvider.<init>(ExternalDocumentationLinkResolver.kt:35)
    at org.jetbrains.dokka.PackageListProvider.class(ExternalDocumentationLinkResolver.kt:35)
    while locating org.jetbrains.dokka.PackageListProvider
      for parameter 4 at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:204)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:10)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:20)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:19)
    while locating org.jetbrains.dokka.PackageDocs
```

**Comment by aalmiray** [comment]
See https://github.com/Kotlin/dokka/issues/213#issuecomment-572133652 for reference

**Comment by leonard84** [comment]
FYI, looks like the linked issue above put the flags in the wrong position, they belong to `configuration` and not `externalDocumentationLink`.

```
noJdkLink = true
noStdlibLink = true
noAndroidSdkLink = true
```
https://github.com/Kotlin/dokka/blob/master/runners/gradle-plugin/MIGRATION.md
