### ISSUE TITLE
ProjectsExtensionImpl.cleanup throws a ConcurrentModificationException

### ISSUE THREAD

**Issue by FRodrigues-BrandenPT** [kordamp/kordamp-gradle-plugins#455]
Hello, when I run this [project](https://github.com/FRodrigues-BrandenPT/kordamp-settings-debug) I get this exception:

```
* Exception is:
java.util.ConcurrentModificationException
        at org.kordamp.gradle.plugin.settings.internal.ProjectsExtensionImpl.cleanup(ProjectsExtensionImpl.groovy:453)
        at org.kordamp.gradle.plugin.settings.internal.ProjectsExtensionImpl.resolveFromConfig(ProjectsExtensionImpl.groovy:155)
        at org.kordamp.gradle.plugin.settings.internal.ProjectsExtensionImpl.access$5(ProjectsExtensionImpl.groovy)
        at org.kordamp.gradle.plugin.settings.internal.ProjectsExtensionImpl$1.settingsEvaluated(ProjectsExtensionImpl.groovy:86)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
```

Probably because this method is removing objects of the iterator?

I'm going to not use the settings plugin for the time being.
Thanks.

**Comment by FRodrigues-BrandenPT** [comment]
Found the problem.
Gradle or IntelliJ added the following statements to the settings.gradle:

```kotlin
include("ThisProjectPlugin")
include("build-config-plugins:ThisProjectPlugin")
findProject(":build-config-plugins:ThisProjectPlugin")?.name = "ThisProjectPlugin"
```

Sorry to bother you.

**Comment by aalmiray** [comment]
OK. So this is not a bug in Kordamp itself, is it?

**Comment by FRodrigues-BrandenPT** [comment]
I'm not sure, because as a user I would expect a plugin error saying that I'm trying to add non-existing projects.
But instead, I got ConcurrentModificationException. So if it's a bug of Kordamp I wouldn't prioritize it.
