### ISSUE TITLE
Integration test plugin causes NPE with Gradle 7.0.2

### ISSUE THREAD

**Issue by eloo** [kordamp/kordamp-gradle-plugins#480]
Hi,

i've just tested if i can upgrade my projects to the latest Gradle version but it seems that the integration test plugin is making trouble. 
During the validation of the gradle scripts the integration test plugin causes a NPE 

```
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:386)
        at org.kordamp.gradle.plugin.integrationtest.IntegrationTestPlugin.adjustConfigurations(IntegrationTestPlugin.groovy:146)
```

Is this a known issue? Or just a new bug?

Best regards
eloo

**Comment by ursjoss** [comment]
I experienced it too. Can also be verified in the reproducer: https://github.com/ursjoss/kordamp-gradle-test-suite/pull/30

**Comment by aalmiray** [comment]
I'm afraid this problem is caused by the removal of `compile` and `runtime` configurations in Gradle 7. I missed updating the plugin. FWIW the `functional-test` plugin has the same issue.

**Comment by ursjoss** [comment]
Seems like it. I merged the initially mentioned PR 30 by downgrading to gradle-wrapper 6.9 and isolating the jump to gradle-7.x. In [PR 31](https://github.com/ursjoss/kordamp-gradle-test-suite/pull/31) I documented three seemingly separate incarnations of probably all the same root cause you mentioned.
