### ISSUE TITLE
Gradle 7.1 generates a warning for aggregated Jacoco report task

### ISSUE THREAD

**Issue by dmurat** [kordamp/kordamp-gradle-plugins#486]
kordamp-gradle-plugins: 0.46.0

```
gw tasks --warning-mode all --stacktrace
...
> Configure project :
The Report.enabled property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the required property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled for more details.
        at org.gradle.api.reporting.internal.SimpleReport.setEnabled(SimpleReport.java:108)
        at org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport_Decorated.setEnabled(Unknown Source)
        at org.kordamp.gradle.plugin.jacoco.JacocoPlugin$3$1.execute(JacocoPlugin.groovy:141)
        at org.kordamp.gradle.plugin.jacoco.JacocoPlugin$3$1.execute(JacocoPlugin.groovy)
        at org.gradle.testing.jacoco.tasks.JacocoReport.reports(JacocoReport.java:78)
        at org.kordamp.gradle.plugin.jacoco.JacocoPlugin$3.execute(JacocoPlugin.groovy:138)
        at org.kordamp.gradle.plugin.jacoco.JacocoPlugin$3.execute(JacocoPlugin.groovy)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
...
```

```
gw --version

------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Oracle Corporation 11.0.11+9-LTS-194)
OS:           Mac OS X 10.16 x86_64
```

Tnx

**Comment by jsajlovic** [comment]
Still there in Gradle 7.4 and kordamp 0.47.0. 

@aalmiray Is there a plan to do this enhancement in the future, perhaps? I see that it's part of a milestone that was closed some time ago.
